
// This file has been generated by the GUI designer. Do not modify.
namespace AggrocubeClient.UI
{
	public partial class SettingsWindow
	{
		private global::Gtk.Table settingsTable;

		private global::Gtk.HButtonBox saveBox;

		private global::Gtk.Button cancelButton;

		private global::Gtk.Button applyButton;

		private global::Gtk.Frame videoFrame;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.Table videoTable;

		private global::Gtk.Label GtkLabel1;

		private global::Gtk.Frame volumeFrame;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Table volumeTable;

		private global::Gtk.Label critterLabel;

		private global::Gtk.HScale CritterSlider;

		private global::Gtk.Label musicLabel;

		private global::Gtk.HScale musicSlider;

		private global::Gtk.Label soundLabel;

		private global::Gtk.HScale soundSlider;

		private global::Gtk.Label volumeLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AggrocubeClient.UI.SettingsWindow
			this.Name = "AggrocubeClient.UI.SettingsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Settings");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-properties", global::Gtk.IconSize.Menu);
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child AggrocubeClient.UI.SettingsWindow.Gtk.Container+ContainerChild
			this.settingsTable = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.settingsTable.WidthRequest = 500;
			this.settingsTable.Name = "settingsTable";
			this.settingsTable.RowSpacing = ((uint)(6));
			this.settingsTable.ColumnSpacing = ((uint)(6));
			// Container child settingsTable.Gtk.Table+TableChild
			this.saveBox = new global::Gtk.HButtonBox ();
			this.saveBox.Name = "saveBox";
			this.saveBox.Spacing = 5;
			this.saveBox.BorderWidth = ((uint)(5));
			this.saveBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child saveBox.Gtk.ButtonBox+ButtonBoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseUnderline = true;
			// Container child cancelButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancel");
			w5.UseUnderline = true;
			w2.Add (w5);
			w1.Add (w2);
			this.cancelButton.Add (w1);
			this.saveBox.Add (this.cancelButton);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.saveBox[this.cancelButton]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child saveBox.Gtk.ButtonBox+ButtonBoxChild
			this.applyButton = new global::Gtk.Button ();
			this.applyButton.CanFocus = true;
			this.applyButton.Name = "applyButton";
			this.applyButton.UseUnderline = true;
			// Container child applyButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Apply");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.applyButton.Add (w10);
			this.saveBox.Add (this.applyButton);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.saveBox[this.applyButton]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.settingsTable.Add (this.saveBox);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.settingsTable[this.saveBox]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child settingsTable.Gtk.Table+TableChild
			this.videoFrame = new global::Gtk.Frame ();
			this.videoFrame.Name = "videoFrame";
			this.videoFrame.ShadowType = ((global::Gtk.ShadowType)(1));
			this.videoFrame.BorderWidth = ((uint)(5));
			// Container child videoFrame.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.videoTable = new global::Gtk.Table (((uint)(3)), ((uint)(1)), false);
			this.videoTable.Name = "videoTable";
			this.videoTable.RowSpacing = ((uint)(6));
			this.videoTable.ColumnSpacing = ((uint)(6));
			this.GtkAlignment1.Add (this.videoTable);
			this.videoFrame.Add (this.GtkAlignment1);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Video</b>");
			this.GtkLabel1.UseMarkup = true;
			this.videoFrame.LabelWidget = this.GtkLabel1;
			this.settingsTable.Add (this.videoFrame);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.settingsTable[this.videoFrame]));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child settingsTable.Gtk.Table+TableChild
			this.volumeFrame = new global::Gtk.Frame ();
			this.volumeFrame.Name = "volumeFrame";
			this.volumeFrame.ShadowType = ((global::Gtk.ShadowType)(1));
			this.volumeFrame.BorderWidth = ((uint)(5));
			// Container child volumeFrame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.volumeTable = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.volumeTable.Name = "volumeTable";
			this.volumeTable.RowSpacing = ((uint)(6));
			this.volumeTable.ColumnSpacing = ((uint)(6));
			// Container child volumeTable.Gtk.Table+TableChild
			this.critterLabel = new global::Gtk.Label ();
			this.critterLabel.Name = "critterLabel";
			this.critterLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Critters");
			this.volumeTable.Add (this.critterLabel);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.volumeTable[this.critterLabel]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child volumeTable.Gtk.Table+TableChild
			this.CritterSlider = new global::Gtk.HScale (null);
			this.CritterSlider.CanFocus = true;
			this.CritterSlider.Name = "CritterSlider";
			this.CritterSlider.Adjustment.Upper = 100;
			this.CritterSlider.Adjustment.PageIncrement = 10;
			this.CritterSlider.Adjustment.StepIncrement = 1;
			this.CritterSlider.DrawValue = true;
			this.CritterSlider.Digits = 0;
			this.CritterSlider.ValuePos = ((global::Gtk.PositionType)(1));
			this.volumeTable.Add (this.CritterSlider);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.volumeTable[this.CritterSlider]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child volumeTable.Gtk.Table+TableChild
			this.musicLabel = new global::Gtk.Label ();
			this.musicLabel.Name = "musicLabel";
			this.musicLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Music");
			this.volumeTable.Add (this.musicLabel);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.volumeTable[this.musicLabel]));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child volumeTable.Gtk.Table+TableChild
			this.musicSlider = new global::Gtk.HScale (null);
			this.musicSlider.CanFocus = true;
			this.musicSlider.Name = "musicSlider";
			this.musicSlider.Adjustment.Upper = 100;
			this.musicSlider.Adjustment.PageIncrement = 10;
			this.musicSlider.Adjustment.StepIncrement = 1;
			this.musicSlider.DrawValue = true;
			this.musicSlider.Digits = 0;
			this.musicSlider.ValuePos = ((global::Gtk.PositionType)(1));
			this.volumeTable.Add (this.musicSlider);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.volumeTable[this.musicSlider]));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child volumeTable.Gtk.Table+TableChild
			this.soundLabel = new global::Gtk.Label ();
			this.soundLabel.Name = "soundLabel";
			this.soundLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Sounds");
			this.volumeTable.Add (this.soundLabel);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.volumeTable[this.soundLabel]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child volumeTable.Gtk.Table+TableChild
			this.soundSlider = new global::Gtk.HScale (null);
			this.soundSlider.CanFocus = true;
			this.soundSlider.Name = "soundSlider";
			this.soundSlider.Adjustment.Upper = 100;
			this.soundSlider.Adjustment.PageIncrement = 10;
			this.soundSlider.Adjustment.StepIncrement = 1;
			this.soundSlider.DrawValue = true;
			this.soundSlider.Digits = 0;
			this.soundSlider.ValuePos = ((global::Gtk.PositionType)(1));
			this.volumeTable.Add (this.soundSlider);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.volumeTable[this.soundSlider]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.volumeTable);
			this.volumeFrame.Add (this.GtkAlignment);
			this.volumeLabel = new global::Gtk.Label ();
			this.volumeLabel.Name = "volumeLabel";
			this.volumeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Volume</b>");
			this.volumeLabel.UseMarkup = true;
			this.volumeFrame.LabelWidget = this.volumeLabel;
			this.settingsTable.Add (this.volumeFrame);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.settingsTable[this.volumeFrame]));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.settingsTable);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 584;
			this.DefaultHeight = 378;
			this.Show ();
			this.cancelButton.Clicked += new global::System.EventHandler (this.OnCancelButtonClicked);
			this.applyButton.Clicked += new global::System.EventHandler (this.OnApplyButtonClicked);
		}
	}
}
