
// This file has been generated by the GUI designer. Do not modify.
namespace AggrocubeClient.UI
{
	public partial class ServerWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AggrocubeClient.UI.ServerWindow
			this.Name = "AggrocubeClient.UI.ServerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ServerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
